### ISSUE TITLE
Handle notifications

### ISSUE THREAD

**Issue by Snunesnk** [Snunesnk/Matcha#24]
The app should be able to show in real time notifications to the user.
A notifications must appear when:
- A user visited your profile
- A user liked your profile
- A user sent you a message
- You got a match (a liked user liked you back)
- A user that previously liked you unliked you

This should be handled with websocket, so it is necessary to implement a websocket communication between front and back

**Comment by chduong42** [comment]
Front is ready. Waiting for back n

**Comment by Snunesnk** [comment]
What to do:
- Plug notifications from back to front
- Show on the navbar icons if a user has received a notification or a message
- Show notifications on real-time (maybe not required ?)
- Show when a new match appear if user is on message page
- Show if a conversation get a new message
- Update conversation in real-time (with read/unread status ?)
