### ISSUE TITLE
Browser : Matching algorithm

### ISSUE THREAD

**Issue by Snunesnk** [Snunesnk/Matcha#26]
The app should implement a matching algorithm, that will take a set of criterias to return a list to the user of profiles that match its criterias

**Comment by chduong42** [comment]
You must cleverly match3 based on:
◦ Same geographic area as the user.
◦ A maximum of common tags.
◦ A maximum “fame rating”.

**Comment by chduong42** [comment]
You will only propose “interesting” profiles. For example, only men for a hetero-
sexual girls. You must manage bisexuality.If the user’s orientation isn’t specified,
they will be considered bisexual.

**Comment by chduong42** [comment]
• You must prioritize showing people from the same geographical area.
• The list must be sortable by age, location, “fame rating”, and common tags.
• The list must be filterable by age, location, “fame rating”, and common tags.

**Comment by chduong42** [comment]
The user must be able to easily get a list of suggestions that match their profile.
• You will only propose “interesting” profiles. For example, only men for a hetero-
sexual girls. You must manage bisexuality.If the user’s orientation isn’t specified,
they will be considered bisexual.
• You must cleverly match3 based on:
◦ Same geographic area as the user.
◦ A maximum of common tags.
◦ A maximum “fame rating”.
• You must prioritize showing people from the same geographical area.
• The list must be sortable by age, location, “fame rating”, and common tags.
• The list must be filterable by age, location, “fame rating”, and common tags.
